import os, sys, json, requests

def main():
    token = os.getenv('GITHUB_PAT')
    if not token:
        print('Error: GITHUB_PAT not set')
        sys.exit(1)
    repo_name = 'affiliate-site'
    owner = 'Turbovod'
    # Check if repo exists
    headers = {
        'Authorization': f'token {token}',
        'Accept': 'application/vnd.github+json'
    }
    get_url = f'https://api.github.com/repos/{owner}/{repo_name}'
    r = requests.get(get_url, headers=headers)
    if r.status_code == 200:
        print('Repo already exists')
        return
    # Create repo
    create_url = 'https://api.github.com/user/repos'
    payload = {
        'name': repo_name,
        'private': False,
        'description': 'Affiliate site generated by Antigravity bot',
        'auto_init': True
    }
    resp = requests.post(create_url, headers=headers, json=payload)
    if resp.status_code in (201, 202):
        print('Repo created successfully')
    else:
        print('Failed to create repo')
        print('Status:', resp.status_code)
        print('Response:', resp.text)
        sys.exit(1)

if __name__ == '__main__':
    main()
